[font]
size = 16

[font.bold]
family = "Monaspace Argon Var"
style = "Medium"

[font.italic]
family = "Monaspace Argon Var"
style = "Regular"

[font.normal]
family = "Monaspace Argon Var"
style = "Light"

[font.offset]
y = 4

[fonts.gh_argon]
size = 16

[fonts.gh_argon.bold]
family = "Monaspace Argon Var"
style = "Medium"

[fonts.gh_argon.italic]
family = "Monaspace Argon Var"
style = "Regular"

[fonts.gh_argon.normal]
family = "Monaspace Argon Var"
style = "Light"

[fonts.gh_argon.offset]
y = 4

[fonts.gh_neon]
size = 16

[fonts.gh_neon.bold]
family = "Monaspace Neon Var"
style = "Bold"

[fonts.gh_neon.italic]
family = "Monaspace Neon Var"
style = "Regular"

[fonts.gh_neon.normal]
family = "Monaspace Neon Var"
style = "Regular"

[fonts.gh_neon.offset]
y = 3

[fonts.ibm_plex_mono]
size = 15
style = "SemiBold"

[fonts.ibm_plex_mono.bold]
family = "BlexMono Nerd Font"

[fonts.ibm_plex_mono.bold_italic]
family = "BlexMono Nerd Font"
style = "Bold Italic"

[fonts.ibm_plex_mono.italic]
family = "BlexMono Nerd Font"
style = "Italic"

[fonts.ibm_plex_mono.normal]
family = "BlexMono Nerd Font"
style = "Text"

[fonts.jetbrains_mono]
size = 15

[fonts.jetbrains_mono.normal]
family = "JetBrainsMono Nerd Font Mono"

[fonts.jetbrains_mono.offset]
y = 5

[fonts.monaco]
size = 14

[fonts.monaco.normal]
family = "Monaco"

[[schemes.github_dimmed.indexed_colors]]
color = "0xd18616"
index = 16

[[schemes.github_dimmed.indexed_colors]]
color = "0xff938a"
index = 17

[schemes.github_dimmed.bright]
black = "0x636e7b"
blue = "0x6cb6ff"
cyan = "0x56d4dd"
green = "0x6bc46d"
magenta = "0xdcbdfb"
red = "0xff938a"
white = "0x768390"
yellow = "0xdaaa3f"

[schemes.github_dimmed.normal]
black = "0x22272e"
blue = "0x6cb6ff"
cyan = "0x56d4dd"
green = "0x6bc46d"
magenta = "0xb083f0"
red = "0xff938a"
white = "0x768390"
yellow = "0xc69026"

[schemes.github_dimmed.primary]
background = "0x22272e"
foreground = "0x768390"
