#!/bin/zsh

export USERNAME=`whoami`
sudo chsh -s $(which zsh) $USERNAME

mkdir -p ~/bin

# DEBIAN specific
if [ -f "/etc/debian_version" ]; then
  sudo apt update
  sudo apt install -y \
    stow \
    tmux \
    fzf \
    ripgrep \
    kitty-terminfo

  brew install jj zellij

  curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux-x86_64.appimage
  chmod u+x nvim.appimage
  ./nvim.appimage --appimage-extract
  ln -s "$(pwd)/squashfs-root/usr/bin/nvim" ~/bin/nvim
  rm -f nvim.appimage

  wget https://github.com/BlakeWilliams/remote-development-manager/releases/latest/download/rdm-linux-amd64
  mv rdm-linux-amd64 ~/bin/rdm
  chmod +x ~/bin/rdm
fi

# GitHub Codespaces specific
if [ -n "${CODESPACES}" ]; then
  # Install bat
  sudo apt install bat -y
  mkdir -p ~/.local/bin
  ln -s /usr/bin/batcat ~/.local/bin/bat
fi

## Install starship
curl -sS https://starship.rs/install.sh | sh -s -- --yes

## Install prezto
# if prezto folder does not exist then clone it
if [ ! -d ~/.zprezto ]; then
  git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"
fi

rm -f ~/.gitconfig # remove any default .zshrc so that stow won't fail

# if ~/.zshrc already exists then append its contents to zsh/.zshrc
if [ -f ~/.zshrc ]; then
  # echo "" >> zsh/.zshrc
  # echo "# Appended from pre-existing ~/.zshrc" >> zsh/.zshrc
  # cat ~/.zshrc >> zsh/.zshrc
  rm -f ~/.zshrc
fi

# if ~/.zprofile already exists then append its contents to zsh/.zprofile
if [ -f ~/.zprofile ]; then
  echo "" >> zsh/.zprofile
  echo "# Appended from pre-existing ~/.zprofile" >> zsh/.zprofile
  cat ~/.zprofile >> zsh/.zprofile
  rm -f ~/.zprofile
fi

stow bin git terminal tmux vim zsh jj -t $HOME

## NEOVIM setup
nvim --headless "+Lazy! sync" +qa

## Download Alacritty terminfo
curl -sSL https://raw.githubusercontent.com/alacritty/alacritty/master/extra/alacritty.info | tic -x -
