#!/bin/zsh

# DEBIAN
if [ -f "/etc/debian_version" ]; then
  sh <(curl -L https://nixos.org/nix/install) --no-daemon

  # source nix-env in place
  . /home/codespace/.nix-profile/etc/profile.d/nix.sh

  nix-env -iA nixpkgs.neovim nixpkgs.starship nixpkgs.zsh-prezto
fi

stow bin
stow git
stow terminal
stow tmux
stow vim
stow zsh
